W5D2/RedditClone/config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :posts, only: [:edit, :update]
  end
  resource :session, only: [:new, :create, :destroy]
  resources :subs do
    resources :posts, only: [:new, :create]
  end
  resources :posts, only: [:show, :destroy] do
    resources :comments, only: :new
  end 
  resources :comments, only: :create
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

W5D2/RedditClone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

W5D2/RedditClone/app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :author,
  primary_key: :id,
  foreign_key: :author_id,
  class_name: :User

  belongs_to :post
end

W5D2/RedditClone/app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true

  belongs_to :sub
  belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User

  has_many :post_subs, inverse_of: :post

  has_many :subs,
    through: :post_subs,
    source: :sub

  has_many :comments 


end

W5D2/RedditClone/app/models/post_sub.rb
class PostSub < ApplicationRecord
  belongs_to :post
  belongs_to :sub 
end

W5D2/RedditClone/app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, :description, presence: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :User

  has_many :post_subs, inverse_of: :sub

  has_many :posts,
  through: :post_subs,
  source: :post

end

W5D2/RedditClone/app/models/user.rb
class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  has_many :subs,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :Sub

  has_many :posts,
  primary_key: :id,
  foreign_key: :author_id,
  class_name: :Post

  has_many :comments,
  primary_key: :id,
  foreign_key: :author_id,
  class_name: :Comment

  attr_reader :password

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user && user.valid_password?(password)
    user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
end

W5D2/RedditClone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  private

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def log_in(user)
    user.reset_session_token
    session[:session_token] = user.session_token
    redirect_to subs_url
  end

  def log_out
    current_user.reset_session_token
    session[:session_token] = nil
    redirect_to new_session_url
  end

  def require_log_in!
    redirect_to new_session_url unless logged_in?
  end

  def ensure_moderator
    current_user.subs.find(params[:id])
  end
end

W5D2/RedditClone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_log_in!

  def new
    @comment = Comment.new
    @comment.post_id = params[:post_id]
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    if @comment.save
      redirect_to sub_url(@comment.post.sub)
      # will send to main sub 
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
    #post_id
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

W5D2/RedditClone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_log_in!, only: [:new, :create, :edit, :update, :destroy]
  def new
    @post = Post.new
    @post.sub_id = params[:sub_id]
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    @post.sub_id = params[:sub_id]

    # params[:sub_ids].each do

    if @post.save
      redirect_to sub_url(@post.sub)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to sub_url(@post.sub)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    redirect_to user_url(@post.author)
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [] )
  end
end

W5D2/RedditClone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )
    if @user
      log_in(@user)
    else
      flash.now[:errors] = ['Invalid Credentials']
      render :new
    end
  end

  def destroy
    log_out
  end
end

W5D2/RedditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_log_in!

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator = current_user
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def edit
    @sub = current_user.subs.find(params[:id])
    # double check later
  end

  def update
    @sub = current_user.subs.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def destroy

  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

W5D2/RedditClone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = current_user
    @user.destroy
    redirect_to new_user_url
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

W5D2/RedditClone/app/helpers/application_helper.rb
module ApplicationHelper
end

W5D2/RedditClone/app/helpers/comments_helper.rb
module CommentsHelper
end

W5D2/RedditClone/app/helpers/posts_helper.rb
module PostsHelper
end

W5D2/RedditClone/app/helpers/sessions_helper.rb
module SessionsHelper
end

W5D2/RedditClone/app/helpers/subs_helper.rb
module SubsHelper
end

W5D2/RedditClone/app/helpers/users_helper.rb
module UsersHelper
end

W5D2/RedditClone/app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

W5D2/RedditClone/app/views/comments/new.html.erb
<h1>Post New Comment</h1>
<h3>Post: <%= @comment.post.title %></h3>

<form action="<%= comments_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Content
    <input type="textarea" name="comment[content]" value="">
  </label>

  <input type="hidden" name="comment[post_id]" value="<%= @comment.post.id %>">

  <input type="submit" value="Create Comment">
</form>

W5D2/RedditClone/app/views/layouts/_errors.html.erb
<%= flash[:errors].join('<br>').html_safe if flash[:errors] %>

W5D2/RedditClone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/errors" %>
    <% if logged_in? %>
      <%= current_user.username %>
      <%= button_to "Sign Out", session_url, method: :delete %>
      <% else %>
      <%= link_to "Sign In", new_session_url %>
      <%= link_to "Sign Up", new_user_url %>
    <% end %>

    <%= yield %>
  </body>
</html>

W5D2/RedditClone/app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

W5D2/RedditClone/app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

W5D2/RedditClone/app/views/posts/edit.html.erb
<h1>Edit <%= @post.title.capitalize %></h1>
<form action="<%= user_post_url %>" method="post">
  <input type="hidden" name="_method" value="PATCH">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>

  <label>URL <em>(optional)</em>
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>

  <label>Content <em>(optional)</em>
    <input type="textarea" name="post[content]" value="<%= @post.content %>">
  </label>

  <button>Update Post</button>
</form>

W5D2/RedditClone/app/views/posts/new.html.erb
<h1>Create Post</h1>
<form action="<%= sub_posts_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

<h3>main sub: <%= @post.sub.title %></h3>

  <label>Title
    <input type="text" name="post[title]" value="">
  </label>

  <label>URL <em>(optional)</em>
    <input type="text" name="post[url]" value="">
  </label>

  <label>Content <em>(optional)</em>
    <input type="textarea" name="post[content]" value="">
  </label>


<input type="hidden" name="post[sub_ids][]" value="<%= @post.sub.id %>">
  <br> <label>Also Post to Other Subs:
      <% Sub.all.each do |sub| %>
        <% unless sub.title == @post.sub.title %>
          <label>
            <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>">
            <%= sub.title %>
          </label>
        <% end %>
      <% end %>
  </label>

  <button>Create Post</button>
</form>

W5D2/RedditClone/app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

W5D2/RedditClone/app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

W5D2/RedditClone/app/views/subs/create.html.erb
<h1>Subs#create</h1>
<p>Find me in app/views/subs/create.html.erb</p>

W5D2/RedditClone/app/views/subs/destroy.html.erb
<h1>Subs#destroy</h1>
<p>Find me in app/views/subs/destroy.html.erb</p>

W5D2/RedditClone/app/views/subs/edit.html.erb
<h1>Subs#edit</h1>
<p>Find me in app/views/subs/edit.html.erb</p>

W5D2/RedditClone/app/views/subs/index.html.erb
<h1>List of Subs</h1>

<% @subs.each do |sub| %>
  <ul>
    <li> <%= link_to "#{sub.title}", sub_url(sub) %></li>
  </ul>
<% end %>

W5D2/RedditClone/app/views/subs/new.html.erb
<h1>Create Sub</h1>
<form action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title
    <input type="text" name="sub[title]" value="">
  </label>

  <label>Description
    <input type="text" name="sub[description]" value="">
  </label>

  <button>Create Sub</button>
</form>

W5D2/RedditClone/app/views/subs/show.html.erb
<h1> <%= @sub.title %> </h1>
<h4> by <strong><%= @sub.moderator.username %></strong> </h4>
<%= @sub.description %>

<h3>Posts</h3>

<article>
  <% @sub.posts.each do |post| %>
  <ul>
  <h4><%= post.title %></h4>
  <li> author: <%= post.author.username %></li>
  <li>content: <%= post.content %></li>

  <% post.comments.each do |comment| %>
<li> <%= comment.content %> </li>
<li> <%= comment.author.username %> </li>
<% end %>
<br>
<%= link_to 'Create Comment', new_post_comment_url(post) %>


  <% if post.author == current_user %>
  <%= link_to "Edit Post", edit_user_post_url(current_user, post) %>
  <% end %>

  <% if post.author == current_user || @sub.moderator == current_user %>
  <%= button_to "Delete Post", post_url(post), method: :delete %>
  <% end %>

  </ul>
  <% end %>
</article>



<%= link_to "New Post", new_sub_post_url(@sub) %><br>
<%= link_to "All Subs", subs_url %>

W5D2/RedditClone/app/views/subs/update.html.erb
<h1>Subs#update</h1>
<p>Find me in app/views/subs/update.html.erb</p>

W5D2/RedditClone/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

W5D2/RedditClone/app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

W5D2/RedditClone/app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

W5D2/RedditClone/app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

W5D2/RedditClone/app/views/users/new.html.erb
<h1>Sign Up</h1>


<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Username
    <input type="text" name="user[username]" value="">
  </label>

  <label>Password
    <input type="password" name="user[password]" value="">
  </label>

  <button>Sign Up</button>

</form>

W5D2/RedditClone/app/views/users/show.html.erb
<h1>Users#show</h1>
<%= current_user.username %>

W5D2/RedditClone/app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>